"""
maintenance_agent.py — Maintenance Recommendation Agent

Responsibilities:
  1. Retrieve relevant knowledge from the RAG knowledge base
  2. Generate a structured maintenance recommendation
  3. Assign risk level based on health score and fault evidence
  4. Format the final health report

LLM usage:
  - If LLM is available: use it to generate natural language recommendation.
  - If LLM unavailable: use deterministic template-based generation.
  The system NEVER fails due to missing LLM.

Reads from state:
  - health_result, fault_result, rca_result, test_id

Writes to state:
  - maintenance_recommendation (structured dict)
  - final_report (human-readable string)
"""

from pathlib import Path
from typing import Optional

from loguru import logger


# ── Template-based recommendation rules ──────────────────────────────────────
MAINTENANCE_TEMPLATES = {
    "CRITICAL": {
        "action": "IMMEDIATE INSPECTION REQUIRED",
        "urgency": "Within 24 hours",
        "steps": [
            "Immediately reduce equipment load if possible",
            "Inspect bearing housing for unusual temperature",
            "Check vibration levels at bearing locations",
            "Plan bearing replacement or overhaul",
            "Consult vibration analysis specialist",
        ],
    },
    "HIGH": {
        "action": "SCHEDULE MAINTENANCE — HIGH PRIORITY",
        "urgency": "Within 1 week",
        "steps": [
            "Schedule bearing inspection within 7 days",
            "Monitor vibration levels at increased frequency (daily)",
            "Check lubrication status and quality",
            "Inspect for contamination or misalignment",
            "Prepare replacement bearing as standby",
        ],
    },
    "MEDIUM": {
        "action": "MONITOR AND SCHEDULE PREVENTIVE MAINTENANCE",
        "urgency": "Within 1 month",
        "steps": [
            "Continue monitoring at standard intervals",
            "Schedule bearing lubrication check",
            "Review operating conditions (load, speed, temperature)",
            "Plan preventive maintenance at next scheduled stop",
        ],
    },
    "LOW": {
        "action": "CONTINUE NORMAL OPERATION",
        "urgency": "Standard schedule",
        "steps": [
            "Maintain standard monitoring schedule",
            "Continue lubrication as per maintenance plan",
            "No immediate action required",
        ],
    },
}


class MaintenanceAgent:
    """
    Generates maintenance recommendations from health analysis results.
    Optionally uses RAG knowledge retrieval and LLM enhancement.
    """

    def __init__(self, knowledge_base_path: Path, use_llm: bool = False):
        self.knowledge_base_path = Path(knowledge_base_path)
        self.use_llm = use_llm
        self._retriever = None

    def _load_retriever(self):
        """Lazily load the RAG retriever."""
        if self._retriever is None:
            try:
                from industrial_health.rag.retriever import KnowledgeRetriever
                self._retriever = KnowledgeRetriever(self.knowledge_base_path)
                self._retriever.load_or_build()
            except Exception as e:
                logger.warning(f"RAG retriever not available: {e}")
                self._retriever = None
        return self._retriever

    def _retrieve_knowledge(self, query: str) -> str:
        """Retrieve relevant knowledge from the knowledge base."""
        retriever = self._load_retriever()
        if retriever is None:
            return "Knowledge base not available."
        try:
            results = retriever.retrieve(query, top_k=3)
            return "\n---\n".join([r["content"] for r in results])
        except Exception as e:
            logger.warning(f"RAG retrieval failed: {e}")
            return "Knowledge retrieval failed."

    def _build_recommendation(
        self,
        risk_level: str,
        fault_label: str,
        probable_cause: str,
        retrieved_knowledge: str,
        test_id: int,
        health_score: float,
    ) -> dict:
        """Build a structured maintenance recommendation."""
        template = MAINTENANCE_TEMPLATES.get(risk_level, MAINTENANCE_TEMPLATES["MEDIUM"])

        return {
            "equipment_id":     f"IMS_Test{test_id}_Bearing",
            "condition":        risk_level,
            "detected_fault":   fault_label,
            "health_score":     health_score,
            "risk_level":       risk_level,
            "probable_cause":   probable_cause,
            "recommended_action": template["action"],
            "urgency":          template["urgency"],
            "maintenance_steps": template["steps"],
            "supporting_knowledge": retrieved_knowledge,
            "disclaimer": (
                "This is a decision-support recommendation generated by an AI system. "
                "It does NOT replace professional engineering judgment. "
                "All maintenance actions should be reviewed by qualified personnel."
            ),
        }

    def _format_final_report(self, state: dict) -> str:
        """Format a human-readable final report from state."""
        health = state.get("health_result", {})
        fault  = state.get("fault_result", {})
        rca    = state.get("rca_result", {})
        maint  = state.get("maintenance_recommendation", {})

        report_lines = [
            "=" * 60,
            "  EQUIPMENT HEALTH REPORT",
            "=" * 60,
            f"  Equipment:       IMS Test {state.get('test_id', 'N/A')} Bearing",
            f"  Timestamp:       {state.get('snapshot_timestamp', 'N/A')}",
            "-" * 60,
            f"  Health Score:    {health.get('health_score', 'N/A')}/100",
            f"  Status:          {health.get('status', 'N/A')}",
            f"  Trend:           {health.get('trend', 'N/A')}",
            f"  Risk Level:      {health.get('risk_level', 'N/A')}",
            "-" * 60,
            f"  Anomaly Status:  {health.get('anomaly_status', 'N/A')}",
            f"  Fault Detected:  {fault.get('fault_label', 'N/A')}",
            f"  Confidence:      {fault.get('confidence', 0.0):.1%}",
            "-" * 60,
            "  PROBABLE CAUSE:",
            f"  {rca.get('probable_cause', 'N/A')}",
            "",
            "  INTERPRETATION:",
            f"  {rca.get('probable_interpretation', 'N/A')}",
            "-" * 60,
            "  MAINTENANCE RECOMMENDATION:",
            f"  Action:   {maint.get('recommended_action', 'N/A')}",
            f"  Urgency:  {maint.get('urgency', 'N/A')}",
            "",
            "  Steps:",
        ]
        for step in maint.get("maintenance_steps", []):
            report_lines.append(f"    • {step}")

        report_lines += [
            "-" * 60,
            "  DISCLAIMER:",
            f"  {maint.get('disclaimer', '')}",
            "=" * 60,
        ]
        return "\n".join(report_lines)

    def run(self, state: dict) -> dict:
        """
        Generate maintenance recommendation and final report.

        Reads:  health_result, fault_result, rca_result, test_id
        Writes: maintenance_recommendation, final_report
        """
        health_result = state.get("health_result", {})
        fault_result  = state.get("fault_result", {})
        rca_result    = state.get("rca_result", {})
        test_id       = state.get("test_id", 1)

        risk_level    = health_result.get("risk_level", "MEDIUM")
        fault_label   = fault_result.get("fault_label", "Unknown")
        health_score  = health_result.get("health_score", 50.0)
        probable_cause = rca_result.get("probable_cause", "Unknown")

        # RAG knowledge retrieval
        query = f"bearing {fault_label} {risk_level} maintenance recommendation"
        retrieved = self._retrieve_knowledge(query)

        # Build structured recommendation
        recommendation = self._build_recommendation(
            risk_level=risk_level,
            fault_label=fault_label,
            probable_cause=probable_cause,
            retrieved_knowledge=retrieved,
            test_id=test_id,
            health_score=health_score,
        )
        state["maintenance_recommendation"] = recommendation

        # Format final report
        state["final_report"] = self._format_final_report(state)
        state["maintenance_agent_status"] = "COMPLETED"

        logger.info(
            f"Maintenance recommendation: {recommendation['recommended_action']} "
            f"(urgency: {recommendation['urgency']})"
        )
        return state
